### ISSUE TITLE
WX Error on OSX when setting task bar icon

### ISSUE THREAD

**Issue by Flameborn** [chrisnorman7/gmp3#1]
It seems that WX is not returning a proper icon when GMP3's task bar icon is set to 'icon.png'. This was added in commit df00e78befec55dc7e1f3ec6e7bd6cddc47ef25c, line 10 of gui/taskbar.py.
As a result, GMP3 has no menus and it stops certain functions from working, e.g. search, as the appropriate menu bindings are not set.

**Comment by chrisnorman7** [comment]
Hi,
Thank you so much for reporting this. Can you give me the exact traceback? I don't use OS X ofte, so it'll be much quicker if you can send me the traceback.

I'm assuming you're using the latest versions of everything?

Thanks again, and let's see if we can't get this fixed nice and fast so you can carry on using GMP.

**Comment by Flameborn** [comment]
Hello,
Thank you.
Yes, I'm on Sierra 10.2.1 Public Beta 4 and everything is the latest, according to pip.
Here's the traceback:

> INFO:root:Working out of directory: /Users/Flameborn/Library/Application Support/GMP3.
> wx._core.wxAssertionError: C++ assertion "err == noErr" failed at /Users/robind/projects/buildbots/macosx-vm4/dist-osx-py35/Phoenix/ext/wxWidgets/src/osx/core/bitmap.cpp(678) in GetIconRef(): Error when constructing icon ref

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Flameborn/Downloads/gmp3/gui/main_frame.py", line 158, in on_show
    self.tb_icon = TaskBarIcon()
  File "/Users/Flameborn/Downloads/gmp3/gui/taskbar.py", line 10, in **init**
    self.SetIcon(wx.Icon(wx.Bitmap('icon.png')), '%s V%s' % (application.name, application.**version**))
SystemError: <class 'wx._core.Icon'> returned a result with an error set

Hope this helps!

**Comment by chrisnorman7** [comment]
OK, that should be fixed in the latest commit.

Sorry for the down time.

Please let me know if it works so I can close this issue.

**Comment by Flameborn** [comment]
Confirmed, it is working now with the latest commit. Thank you very much!
