### ISSUE TITLE
It takes ages to clone this repo

### ISSUE THREAD

**Issue by ghost** [chrisnorman7/gmp3#3]
It shouldn't weigh 74 megabytes

**Comment by chrisnorman7** [comment]
I understand. I accidentally added a load of MP3's a while ago, and I don't think I can remove them from the .git folder.

**Comment by manuelcortez** [comment]
If you don't mind about lack of the full history, you can add --dept=1 when cloning the repo so it will create a shallow clone with the last commit. [More info about it here](https://git-scm.com/docs/git-clone)
